services:
  postgres:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=walkit
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=walkit
      - TZ=Asia/Seoul
    volumes:
      - wkt_pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local-bridge

volumes:
  wkt_pg_data:

networks:
  local-bridge:
    driver: bridge