name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: |
          mkdir -p src/main/resources
          mkdir -p src/test/resources
          echo "${{ secrets.APP_DEPLOY_YML }}" > src/main/resources/application.yml
          echo "${{ secrets.APP_JWT_YML }}" > src/main/resources/application-jwt.yml
          echo "${{ secrets.APP_OAUTH_YML }}" > src/main/resources/application-oauth.yml
          echo "${{ secrets.APP_TEST_YML }}" > src/test/resources/application-test.yml

      - name: 빌드하기 (테스트 제외)
        run: ./gradlew clean build -x test

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t walkit-server .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag walkit-server ${{ steps.login-ecr.outputs.registry }}/walkit-server:latest

      - name: ECR에 Docker 이미지 push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/walkit-server:latest

      - name: start-server.sh 생성 (from Secrets)
        run: |
          mkdir -p scripts
          sed "s|##DOCKER_IMAGE##|${{ steps.login-ecr.outputs.registry }}/walkit-server:latest|g" \
            <<< "${{ secrets.START_SERVER_SCRIPT_TEMPLATE }}" > ./scripts/start-server.sh
          chmod +x ./scripts/start-server.sh

      - name: 압축하기
        run: tar -czvf $GITHUB_SHA.tar.gz appspec.yml scripts

      - name: S3에 프로젝트 폴더 업로드하기
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://walk-server/$GITHUB_SHA.tar.gz

      - name: Code Deploy를 활용해 EC2에 프로젝트 코드 배포
        run: |
          aws deploy create-deployment \
          --application-name walkit-server \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name Production \
          --s3-location bucket=walk-server,bundleType=tgz,key=$GITHUB_SHA.tar.gz \
